import { Box, Flex, Text } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>いちアラ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box px="4">
          <Flex mt="16" justifyContent="center" alignItems="center">
            <Image
              src="/ichiara-white.png"
              width={90}
              height={90}
              alt="ロゴ画像"
            />
            <Text fontWeight="bold" color="primary" fontSize="3xl">
              いちアラ
            </Text>
          </Flex>

          <Text textAlign="center" mt="4" fontWeight="bold" fontSize="2xl">
            {'電車、バスで寝過ごさない。乗り過ごさない🌷'}
          </Text>

          <Box mt="12">
            <Flex justifyContent="center">
              <Image
                src="/main-app.png"
                width={200}
                height={400}
                alt="アプリイメージ"
              />
            </Flex>
          </Box>
        </Box>
      </main>
    </>
  );
}
